//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcUsuario
    {
        public int id { get; set; }
        public string eMail { get; set; }
        public string password { get; set; }
        public int tipoUsuario { get; set; }
        public int idEmpleado { get; set; }
        public int status { get; set; }
    }
}
