//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotizador.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IDEAAPPEntities : DbContext
    {
        public IDEAAPPEntities()
            : base("name=IDEAAPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mvcCnfDireccion> mvcCnfDireccion { get; set; }
        public virtual DbSet<mvcCngConsecutivo> mvcCngConsecutivo { get; set; }
        public virtual DbSet<mvcConfig> mvcConfig { get; set; }
        public virtual DbSet<mvcConfigMail> mvcConfigMail { get; set; }
        public virtual DbSet<mvcCStatus> mvcCStatus { get; set; }
        public virtual DbSet<mvcEmpleadosSL> mvcEmpleadosSL { get; set; }
        public virtual DbSet<mvcUsuario> mvcUsuario { get; set; }
        public virtual DbSet<mvcUsuarioSL> mvcUsuarioSL { get; set; }
        public virtual DbSet<mvcCotizacionDet> mvcCotizacionDet { get; set; }
        public virtual DbSet<mvcCotizacionEnc> mvcCotizacionEnc { get; set; }
    }
}
