//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotizador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcConfig
    {
        public int Id { get; set; }
        public string MonedaMat { get; set; }
        public string MonedaServ { get; set; }
        public double PorcImp { get; set; }
        public double MargenMat { get; set; }
        public double MargenMO { get; set; }
        public double PesoxDolar { get; set; }
        public double DolarxPeso { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Pagina { get; set; }
        public string Correo { get; set; }
        public string Ruta { get; set; }
        public double TipoCambio { get; set; }
        public int DiasCotizacion { get; set; }
        public double MargenInd { get; set; }
        public double PorcIndMat { get; set; }
        public double PorcIndMO { get; set; }
        public string CondComer { get; set; }
    }
}
