//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotizador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcCngConsecutivo
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string PrefijoCot { get; set; }
        public string anio { get; set; }
        public string NumeroCot { get; set; }
        public string Ubicacion { get; set; }
    }
}
