//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotizador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcCnfDireccion
    {
        public int Id { get; set; }
        public string Ubicacion { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Pagina { get; set; }
        public string Correo { get; set; }
    }
}
