//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotizador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcConfigMail
    {
        public int Id { get; set; }
        public string tipo { get; set; }
        public string emailEnvio { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string emailRecepcion { get; set; }
        public string asunto { get; set; }
        public string mensaje { get; set; }
        public Nullable<int> puerto { get; set; }
        public string host { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public double User3 { get; set; }
        public double User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public System.DateTime User7 { get; set; }
        public System.DateTime User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
    }
}
