//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotizador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mvcEmpleadosSL
    {
        public int id { get; set; }
        public string EmpID { get; set; }
        public string Name { get; set; }
        public int status { get; set; }
    }
}
